user: "boss"
dbname: "comments_service"
password: "p0$TGR3s$"
host: "127.0.0.1"
port: 5432
sslmode: "disable"
max_open_conns: 10
timer: 1
comment_db: "postgres"
server_adress: ":8083"
grpc_port: ":50051"